---
- name: Copy argononed.conf
  become: yes
  ansible.builtin.copy:
    src: argononed.conf
    dest: /etc/argononed.conf
    mode: '0666'
    owner: root
    group: root

- name: Restart argononed.service
  become: yes
  ansible.builtin.systemd:
    name: argononed.service
    state:  restarted
