---
- name: Check argonone-config command exists
  command: which argonone-uninstall
  ignore_errors: true
  register: which_command

- block:
    - name: Download argon1.sh
      ansible.builtin.get_url:
        url: "https://download.argon40.com/argon1.sh"
        dest: /tmp/argon1.sh
        mode: '0755'
    
    - name: Run installing script
      become: yes
      ansible.builtin.shell:
        cmd: ./argon1.sh
        chdir: /tmp
      args:
        executable: /bin/bash

    - name: Delete argon1.sh
      ansible.builtin.file:
        path: /tmp/argon1.sh
        state: absent
  when: which_command.rc | int != 0

- name: Include configuration task
  ansible.builtin.include_tasks:
    file: configure.yml
