---
- name: Check argonone-uninstall command exists
  command: which argonone-uninstall
  ignore_errors: true
  changed_when: false
  register: which_command

- name: Execute uninstalling argonone commands
  become: yes
  ansible.builtin.expect:
    command: argonone-uninstall
    responses:
      "Press Y to continue:": Y

- name: Remove files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/bin/argonone-ir
    - /usr/bin/argonone-config
    - /etc/argononed.conf  